// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSource } from "./MediaSource";
import type { MediaTimestamps } from "./MediaTimestamps";

export interface MediaState { trackId: string | null, title: string, artists: Array<string>, album: string | null, artwork: string | null, duration: number | null, position: number | null, isPlaying: boolean, source: MediaSource, timestamps: MediaTimestamps | null, }